#!/bin/bash

################################################################################################################
# NAMA SCRIPT        : TRUSTPOSITIF-RPZ-DNS-ZONE-UPDATER.SH
# FUNGSI             : MEMPERBARUI ZONA DNS DENGAN DATA TRUSTPOSITIF, WHITELIST DAN SAFESEARCH
# DESKRIPSI          : SCRIPT INI MENGUNDUH DATA DARI BERBAGAI SUMBER DAN MENGONVERSINYA KE FORMAT RPZ UNTUK BIND.
# AUTHOR             : HARRY DERTIN SUTISNA
# WAKTU & TANGGAL    : JAKARTA, 25 MARET 2025
################################################################################################################

# Warna ANSI
MERAH="\033[1;31m"
HIJAU="\033[1;32m"
KUNING="\033[1;33m"
CYAN="\033[1;36m"
MAGENTA="\033[1;35m"
BIRU="\033[1;34m"
PUTIH="\033[1;37m"
HITAM="\033[1;30m"
ABUABU="\033[1;90m"
MERAH_TUA="\033[1;91m"
HIJAU_TUA="\033[1;92m"
KUNING_TUA="\033[1;93m"
CYAN_TUA="\033[1;96m"
MAGENTA_TUA="\033[1;95m"
BIRU_TUA="\033[1;94m"
PUTIH_TUA="\033[1;97m"
RESET="\033[0m"

# Variabel
URL_TRUSTPOSITIF="https://raw.githubusercontent.com/alsyundawy/TrustPositif-To-RPZ-Binary/refs/heads/main/alsyundawy-blocklist/alsyundawy_blacklist_v2.txt"


FILE_TRUSTPOSITIF="/etc/bind/zones/trustpositif.zones"

# Fungsi untuk menampilkan pesan berwarna
function cetak_pesan() {
    echo -e "$1$2${RESET}"
}

cetak_pesan "$CYAN" "PEMBAHARUAN DATABASE INTERNET SEHAT TRUSTPOSITIF DIPROSES"

# Banner dengan warna
echo -e "${MAGENTA}
   _   _   _   _   _     _   _     _   _   _   _   _   _   _   _   _   _  
  / \ / \ / \ / \ / \   / \ / \   / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ 
 ( H | A | R | R | Y ) ( D | S ) ( A | L | S | Y | U | N | D | A | W | Y )
  \_/ \_/ \_/ \_/ \_/   \_/ \_/   \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ 
${RESET}"

echo -e "${CYAN}############################################################################${RESET}"
echo -e "${CYAN}##                                                                        ##${RESET}"
echo -e "${CYAN}##${MERAH}           PEMBAHARUAN DATABASE INTERNET SEHAT TRUSTPOSITIF             ${CYAN}##${RESET}"
echo -e "${CYAN}##${MAGENTA}                        UNTUK DNS FILTER ISP                            ${CYAN}##${RESET}"
echo -e "${CYAN}##                                                                        ##${RESET}"
echo -e "${CYAN}##${HIJAU}      SCRIPT INI DIBUAT & DIMODIFIKASI OLEH HARRY DS ALSYUNDAWY         ${CYAN}##${RESET}"
echo -e "${CYAN}##${BIRU}         ALSYUNDAWY@GMAIL.COM | 08568515212 | ALSYUNDAWY.COM            ${CYAN}##${RESET}"
echo -e "${CYAN}##${KUNING}                     PADA TANGGAL 25 MARET 2025                       ${CYAN}##${RESET}"
echo -e "${CYAN}##                                                                        ##${RESET}"
echo -e "${CYAN}############################################################################${RESET}"

# Fungsi untuk membuat header RPZ
generate_rpz_header() {
    cat << EOF
;
; RPZ File Generated by TRUSTPOSITIF-RPZ-DNS-ZONE-UPDATER.SH
; Dibuat pada $(date '+%Y-%m-%d %H:%M:%S')
; Author: HARRY DERTIN SUTISNA ALSYUNDAWY
; Email: alsyundawy@gmail.com
; WhatsApp/Telegram/Call: +628568515212 & +6281298986464 (WHATSAPP/TELEGRAM/CALL)
; HOMEPAGE: https://github.com/alsyundawy
;
;
\$TTL 300
@ IN SOA dns.domain.net.id. hostmaster.domain.net.id. (
    $(date '+%y%m%d%H%M') ; Serial
    10800      ; Refresh
    120        ; Retry
    604800     ; Expire
    3600  )    ; Minimum TTL
@ IN NS lamanlabuh.resolver.id.
EOF
}

# Fungsi untuk mengunduh dan memproses TrustPositif
generate_trustpositif_rpz() {
    cetak_pesan "$HIJAU" "Mengunduh data TrustPositif..."
    if ! curl -k "$URL_TRUSTPOSITIF" | tr '[:upper:]' '[:lower:]' > "$TMP_TRUSTPOSITIF"; then
        cetak_pesan "$MERAH" "[ERROR] Gagal mengunduh data TrustPositif."
        exit 1
    fi

    cetak_pesan "$HIJAU" "Mengonversi data TrustPositif ke format RPZ..."
    {
        generate_rpz_header
        awk '/^[^#]/ {print $1 " 3600 IN CNAME " CNAME_TRUSTPOSITIF; print "*." $1 " 3600 IN CNAME " CNAME_TRUSTPOSITIF}' CNAME_TRUSTPOSITIF="$CNAME_TRUSTPOSITIF" "$TMP_TRUSTPOSITIF"
    } > "$FILE_TRUSTPOSITIF"
}


# Fungsi untuk memeriksa file zona
check_zone_files() {
    cetak_pesan "$HIJAU" "Memeriksa file zona..."
    for file in "$FILE_TRUSTPOSITIF" "$FILE_WHITELIST" "$FILE_SAFESEARCH"; do
        if ! named-checkzone "$(basename "$file" .zones)" "$file" > /dev/null 2>&1; then
            cetak_pesan "$MERAH" "[ERROR] Kesalahan dalam file zona $(basename "$file")."
            exit 1
        fi
    done
}

# Fungsi utama
main() {
    cetak_pesan "$CYAN" "MEMULAI PEMBARUAN DATABASE DNS..."
    generate_trustpositif_rpz
    check_zone_files

    cetak_pesan "$HIJAU" "[BERHASIL] Semua file zona berhasil diperbarui dan diverifikasi."
}

main
